language: go
env:
  - TEST_ROOT=$HOME/test
go:
  - 1.4
before_install:
  - mkdir $TEST_ROOT
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - make cover
after_success:
  - bash -c "goveralls -covermode=set -service=travis-ci -coverprofile=fsmq/.cover.out | tee"
