language: go
env:
  - TEST_ROOT=$HOME/test
go:
  - 1.4
before_install:
  - mkdir $TEST_ROOT
  - go get gopkg.in/logex.v1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

  - go get github.com/klauspost/crc32
  - go get github.com/chzyer/flagx
script:
  - make cover
  - bash -c "goveralls -service=travis-ci -coverprofile=fsmq/.cover.out | tee"
